spring:
  profiles:
    active: dev
  application:
    name: gadget-mart-ms


logging:
  level:
    root: info
    org:
      springframework:
        web: info


server:
  port: 7042
  context-path: /gadget-mart


eureka:
    instance:
        instanceId: softlogic-ms
        metadata-map:
            management:
                context-path: /api/management
        health-check-url-path: /api/management/health

management:
    context-path: /management

security:
  basic:
    enabled: false
